func_sample/diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('update/<int:pk>/', views.update, name='update'), # /update/1
    path('delete/<int:pk>/', views.delete, name='delete'), # /diary/delete/1
    path('detail/<int:pk>/', views.detail, name='detail') # /diary/detail/1
]

func_sample/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls'))
]

func_sample/diary/models.py
from django.db import models
# djangoでは、datetime.nowの代わりに、timezone.nowで現在日付・時刻を取得する
from django.utils import timezone

# models.Modelを継承
class Day(models.Model):
    """モデルができたらデータベースに反映"""
    # id = models.AutoField(primary_key=True)
    title = models.CharField('タイトル', max_length=200)
    text = models.TextField('本文')
    date = models.DateTimeField('日付', default=timezone.now)

func_sample/diary/forms.py
from django import forms
from .models import Day


class DayCreateForm(forms.ModelForm):

    class Meta:
        model = Day
        fields = '__all__' # ('title', 'text', 'date')

func_sample/diary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import DayCreateForm
from .models import Day

# Create your views here.

def index(request):
    context = {
        'day_list': Day.objects.all(), #モデル名.objects.allでモデルの情報を全てとる
    }
    return render(request, 'diary/day_list.html', context)

def add(request):
    # 送信内容を元にフォームを作成。POSTじゃなければ、空のフォーム
    form = DayCreateForm(request.POST or None)

    # method=POST つまり送信ボタン押下時、入力内容が問題なければ
    if request.method == 'POST' and form.is_valid():
        form.save()
        # postがうまくいけばすぐリダイレクト
        return redirect('diary:index')

    # 通常時のページアクセスや、入力内容に誤りがあればまたページを表示
    context = {
        'form':form
    }

    return render(request, 'diary/day_form.html', context)


def update(request, pk):
    # urlのpkを基に、Dayを取得
    day = get_object_or_404(Day, pk=pk)

    # フォームに取得したDayを紐づける
    form = DayCreateForm(request.POST or None, instance=day)

    # method=POST、つまり送信ボタン押下時、入力内容が問題なければ
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('diary:index')

    # 通常時のページアクセスや、入力内容に誤りがあればまたページを再表示
    context = {
        'form':form
    }
    return render(request, 'diary/day_form.html', context)


def delete(request, pk):
    # urlのpkを基に、Dayを取得
    day = get_object_or_404(Day, pk=pk)

    # method=POST、つまり送信ボタン押下時、入力内容が問題なければ
    if request.method == 'POST':
        day.delete()
        return redirect('diary:index')

    # 通常時のページアクセスや、入力内容に誤りがあればまたページを再表示
    context = {
        'day':day
    }
    return render(request, 'diary/day_confirm_delete.html', context)

def detail(request, pk):
    # urlのpkを基に、Dayを取得
    day = get_object_or_404(Day, pk=pk)

    # 通常時のページアクセスや、入力内容に誤りがあればまたページを再表示
    context = {
        'day':day
    }
    return render(request, 'diary/day_detail.html', context)

func_sample/diary/templates/diary/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block extracss %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <div class="container">
    <nav class="nav">
      <a class="nav-link" href="{% url 'diary:index' %}">一覧</a>
      <a class="nav-link" href="{% url 'diary:add' %}">追加</a>
    </nav>


    {% block content %}
    {% endblock %}
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

func_sample/diary/templates/diary/day_confirm_delete.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
  <table class="table">
    <tr>
      <th>{{day.title.label}}</th>
      <td>{{day.title}}</td>
    </tr>
    <tr>
      <th>本文</th>
      <td>{{day.text}}</td>
    </tr>
    <tr>
      <th>日付</th>
      <td>{{day.date}}</td>
    </tr>
  </table>
<p>こちらのデータを削除します</p>
<button type="submit", class="btn btn-primary">送信</button>
<!-- POSTでのおまじない -->
{% csrf_token %}
</form>
{% endblock %}

func_sample/diary/templates/diary/day_detail.html
{% extends 'diary/base.html' %}

{% block content %}
<!-- 空文字なら現在開いているurl -->
  <table class="table">
    <tr>
      <th>{{day.title.label}}</th>
      <td>{{day.title}}</td>
    </tr>
    <tr>
      <th>本文</th>
      <td>{{day.text | linebreaksbr}}</td>
    </tr>
    <tr>
      <th>日付</th>
      <td>{{day.date}}</td>
    </tr>
  </table>
{% endblock %}

func_sample/diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block content %}
<!-- 空文字なら現在開いているurl -->
<form action="" method="POST">
<!-- 下記でモデルの内容をフォームに自動反映 -->
<!-- {{form.as_ul}} -->
<!-- {{form.as_p}} -->
  <table class="table">
    <tr>
      <th>{{form.title.label}}</th>
      <td>{{form.title}}</td>
    </tr>
    <tr>
      <th>本文</th>
      <td>{{form.text}}</td>
    </tr>
    <tr>
      <th>日付</th>
      <td>{{form.date}}</td>
    </tr>
  </table>
<button type="submit", class="btn btn-primary">送信</button>
<!-- POSTでのおまじない -->
{% csrf_token %}
</form>
{% endblock %}

func_sample/diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}

{% block content %}
<h1>日記一覧</h1>
<table class="table">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>日付</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
<tbody>
{% for day in day_list %}
<tr>
  <td><a href="{% url 'diary:detail' day.pk %}">{{day.title}}</a></td>
  <td>{{day.date}}</td>
  <!-- day.pkでプライマリーキー -->
  <td><a href="{% url 'diary:update' day.pk %}">更新</a></td>
  <td><a href="{% url 'diary:delete' day.pk %}">削除</a></td>
</tr>
{% endfor %}
</tbody>
</table>
{% endblock %}